### ISSUE TITLE
Upcoming rename of `@prisma/sdk` to `@prisma/internals` with Prisma 4

### ISSUE THREAD

**Issue by janpio** [omar-dulaimi/prisma-yup-generator#10]
Hey,

Jan from Prisma Engineering here.
 
Quick heads up that we will soon rename our `@prisma/sdk` package to `@prisma/internals` with Prisma 4, which we plan to release on June 28th (soon!). 

The `@prisma/sdk` package was meant as an Prisma internal package only, but somehow it leaked out over time and is now used across all kinds of tools - including yours of course 😄

With the rename of the Npm package we want to make it clearer that we can not give any API guarantees for `@prisma/internals`, might need to introduce breaking changes to the API from time to time and will not follow semantic versioning (breaking changes only in major upgrade) with it. We think that it is better communicated with `internals` than with `sdk`.
With Prisma 4, besides the package name nothing should change though.

Additionally it would be super helpful if you could help us gain an understanding where, how and why you are using `@prisma/sdk` (soon `@prisma/internals`, remember 😀) to achieve, what exactly. We want to cleanup that package and your feedback will be valuable to us to define a better API.

Looking forward to your feedback.

Best
Jan & your friends at Prisma

PS: Are you using `Prisma.dmmf` from `import { Prisma } from '@prisma/client'` in your code somewhere by chance? That will also change soon and not include the `Prisma.dmmf.schema` sub property. Instead you can use `getDmmf` from `@prisma/internals` moving forward.

**Comment by Jolg42** [comment]
Note: You can try prisma packages on the `dev` tag on npm, like `@prisma/internals@3.16.0-dev.84`

**Comment by omar-dulaimi** [comment]
Hey @janpio @Jolg42 

Thanks for the heads up. I agree that `internals` is a better name for something that could break every now and then. The old name `sdk` conveyed that it was something Prisma exposed for the developers out there for use, like my projects for example.

I currently do use `Prisma.dmmf`, I appreciate letting me know about the alternative.

The `@prisma/internals` is super useful in the context of generators. I see it as one of Prisma's greatest selling points. We're not limited by the features the Prisma team builds(we are very appreciative of). The community can always come up with creative and interesting ways a piece of software can be used.

One thing I'd like to see in the future is input object types with model attributes. Currently they are separated, and manual work has to be done in order to produce schemas that have the same attributes like the model fields. Like

``` js
isUnique
isId
isReadOnly
hasDefaultValue
default
isGenerated
isUpdatedAt 
```

I'll try to check the dev releases soon.

Thank you for making Prisma great.

**Comment by Jolg42** [comment]
Thanks @omar-dulaimi for your feedback!

Note: About `Prisma.dmmf` it's not going away, only `Prisma.dmmf.schema` is.

**Comment by Jolg42** [comment]
@omar-dulaimi Prisma 4.0.0 was published on Tuesday :canoe: 

The internal package `@prisma/sdk`
- was published for the last time to ease the upgrade (in the future we might reuse the package name, but its content will be different)
- marked deprecated on npm
- available under the new, more explicit package name `@prisma/internals`.

If you know people affected by this, feel free to point them to this [GitHub discussion](https://github.com/prisma/prisma/discussions/13877).
It will help us understand where, how, and why people are using it, so we can define a better API.

Note: I posted your earlier comment of your current usage in that discussion to centralize the usage feedback.
